/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.11 C:\Users\fgarr\Documents\lab\youtube3d\apps\admin\public\assets\cinema10.glb --types 
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube012: THREE.Mesh
    Cube011: THREE.Mesh
    Cube013: THREE.Mesh
    collision_enter: THREE.Mesh
    Cube: THREE.Mesh
    Cube001: THREE.Mesh
    collision_enter001: THREE.Mesh
    Cube002: THREE.Mesh
    Cube004: THREE.Mesh
    Cube005: THREE.Mesh
    Cube006: THREE.Mesh
    Cube007: THREE.Mesh
    Cube008: THREE.Mesh
    Cube009: THREE.Mesh
    Cube010: THREE.Mesh
    stairs: THREE.Mesh
    Cube003: THREE.Mesh
    Neon: THREE.Mesh
    Neon001: THREE.Mesh
  }
  materials: {
    ['Marble.004']: THREE.MeshStandardMaterial
    ['black concrete']: THREE.MeshStandardMaterial
    ['black concrete.002']: THREE.MeshStandardMaterial
    Marble: THREE.MeshStandardMaterial
    Plain: THREE.MeshStandardMaterial
    ['Black concrete']: THREE.MeshStandardMaterial
    ['Plain black']: THREE.MeshStandardMaterial
    Neon: THREE.MeshStandardMaterial
    ['Neon.001']: THREE.MeshStandardMaterial
  }
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/cinema10.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube012.geometry} material={materials['Marble.004']} position={[-4.896, 3.708, 0]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[1, 1, 40.262]} />
      <mesh geometry={nodes.Cube011.geometry} material={materials['black concrete']} position={[-3.717, 3.673, -16.906]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.Cube013.geometry} material={materials['black concrete.002']} position={[3.514, 3.673, -16.906]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.collision_enter.geometry} material={nodes.collision_enter.material} position={[33.1, 4.273, -12.94]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-1, -4.581, -3.691]} />
      <mesh geometry={nodes.Cube.geometry} material={materials.Marble} position={[21.836, 8.459, -6.753]} />
      <mesh geometry={nodes.Cube001.geometry} material={materials['black concrete']} position={[3.354, 3.827, -9.275]} />
      <mesh geometry={nodes.collision_enter001.geometry} material={nodes.collision_enter001.material} position={[18.952, 0.36, -12.94]} scale={[13.404, 0.375, 3.691]} />
      <mesh geometry={nodes.Cube002.geometry} material={materials.Marble} position={[-0.304, 0, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cube004.geometry} material={materials.Plain} position={[0, 7.377, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cube005.geometry} material={materials.Marble} position={[4.617, 9.36, 0]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[-1, -1, -40.426]} />
      <mesh geometry={nodes.Cube006.geometry} material={materials['Black concrete']} position={[51.298, 9.36, 0]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.Cube007.geometry} material={materials.Marble} position={[27.615, 0.009, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[1.009, 1, 1]} />
      <mesh geometry={nodes.Cube008.geometry} material={materials.Marble} position={[27.69, 9.187, -16.527]} rotation={[Math.PI, 0, Math.PI / 2]} scale={[9.368, 23.816, 0.03]} />
      <mesh geometry={nodes.Cube009.geometry} material={materials.Marble} position={[27.557, 9.328, 16.619]} rotation={[Math.PI, 0, Math.PI / 2]} scale={[9.368, 23.816, 0.03]} />
      <mesh geometry={nodes.Cube010.geometry} material={materials['Plain black']} position={[27.722, 18.701, 0.164]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={[-1, -1, -10.203]} />
      <mesh geometry={nodes.stairs.geometry} material={materials.Marble} position={[21.291, 1.721, 6.26]} scale={[1, 1, 0.815]} />
      <mesh geometry={nodes.Cube003.geometry} material={materials['black concrete']} position={[51.162, 10.214, 0]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={0.568} />
      <mesh geometry={nodes.Neon.geometry} material={materials.Neon} position={[-3.619, 7.289, -0.006]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[-0.066, -16.558, -0.065]} />
      <mesh geometry={nodes.Neon001.geometry} material={materials['Neon.001']} position={[3.346, 7.289, -0.006]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[-0.066, -16.558, -0.065]} />
    </group>
  )
}

useGLTF.preload('/cinema10.glb')
