/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 C:\Users\fgarr\Documents\lab\youtube3d\apps\admin\public\assets\cinema6.glb --types 
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube002: THREE.Mesh
    Cube001: THREE.Mesh
    Cube004: THREE.Mesh
    Cube005: THREE.Mesh
    Cube006: THREE.Mesh
    Cube007: THREE.Mesh
    Plane: THREE.Mesh
    Cube008: THREE.Mesh
    Cube009: THREE.Mesh
    Cube010: THREE.Mesh
  }
  materials: {
    Marble: THREE.MeshStandardMaterial
    Plain: THREE.MeshStandardMaterial
    ['Material.009']: THREE.MeshStandardMaterial
    ['Material.010']: THREE.MeshStandardMaterial
    ['Material.011']: THREE.MeshStandardMaterial
    ['Material.012']: THREE.MeshStandardMaterial
    ['Material.013']: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/cinema6.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube002.geometry} material={materials.Marble} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cube001.geometry} material={materials.Plain} position={[-3.704, 3.708, 0]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.Cube004.geometry} material={materials.Plain} position={[0, 7.377, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cube005.geometry} material={materials.Plain} position={[3.709, 9.36, 0]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.Cube006.geometry} material={materials['Material.009']} position={[51.298, 9.36, 0]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={[9.368, 16.641, 0.03]} />
      <mesh geometry={nodes.Cube007.geometry} material={materials['Material.010']} position={[27.722, 0.009, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[24.003, 16.641, 0.03]} />
      <mesh geometry={nodes.Plane.geometry} material={nodes.Plane.material} position={[23.543, 6.912, 16.7]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={[-19.646, -1, -6.876]} />
      <mesh geometry={nodes.Cube008.geometry} material={materials['Material.011']} position={[27.69, 9.187, -16.527]} rotation={[Math.PI, 0, Math.PI / 2]} scale={[9.368, 23.816, 0.03]} />
      <mesh geometry={nodes.Cube009.geometry} material={materials['Material.012']} position={[27.557, 9.403, 16.619]} rotation={[Math.PI, 0, Math.PI / 2]} scale={[9.368, 23.816, 0.03]} />
      <mesh geometry={nodes.Cube010.geometry} material={materials['Material.013']} position={[27.722, 18.701, -0.116]} rotation={[-Math.PI / 2, 0, 0]} scale={[24.003, 16.641, 0.03]} />
    </group>
  )
}

useGLTF.preload('/cinema6.glb')
