/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 C:\Users\fgarr\Documents\lab\youtube3d\apps\admin\public\assets\cinema8.glb --types 
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube002: THREE.Mesh
    Cube001: THREE.Mesh
    Cube004: THREE.Mesh
    Cube005: THREE.Mesh
    Cube006: THREE.Mesh
    Cube007: THREE.Mesh
    Cube008: THREE.Mesh
    Cube009: THREE.Mesh
    Cube010: THREE.Mesh
    stairs: THREE.Mesh
    Cube003: THREE.Mesh
    Neon: THREE.Mesh
    Neon001: THREE.Mesh
  }
  materials: {
    Plain: THREE.MeshStandardMaterial
    Marble: THREE.MeshStandardMaterial
    ['Plain black']: THREE.MeshStandardMaterial
    ['Black concrete']: THREE.MeshStandardMaterial
    ['black concrete']: THREE.MeshStandardMaterial
    Neon: THREE.MeshStandardMaterial
    ['Neon.001']: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/cinema8.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube002.geometry} material={materials.Plain} position={[-0.304, 0, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cube001.geometry} material={materials.Marble} position={[-3.704, 3.708, 0]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.Cube004.geometry} material={materials['Plain black']} position={[0, 7.377, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cube005.geometry} material={materials.Marble} position={[4.617, 9.36, 0]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[-1, -1, -40.426]} />
      <mesh geometry={nodes.Cube006.geometry} material={materials['Black concrete']} position={[51.298, 9.36, 0]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.Cube007.geometry} material={materials.Marble} position={[27.615, 0.009, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[1.009, 1, 1]} />
      <mesh geometry={nodes.Cube008.geometry} material={materials.Marble} position={[27.69, 9.187, -16.527]} rotation={[Math.PI, 0, Math.PI / 2]} scale={[9.368, 23.816, 0.03]} />
      <mesh geometry={nodes.Cube009.geometry} material={materials.Marble} position={[27.557, 9.328, 16.619]} rotation={[Math.PI, 0, Math.PI / 2]} scale={[9.368, 23.816, 0.03]} />
      <mesh geometry={nodes.Cube010.geometry} material={materials['Plain black']} position={[27.722, 18.701, -0.016]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={[-1, -1, -10.203]} />
      <mesh geometry={nodes.stairs.geometry} material={materials.Marble} position={[21.291, 1.721, 3.731]} />
      <mesh geometry={nodes.Cube003.geometry} material={materials['black concrete']} position={[51.162, 10.214, 0]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={0.568} />
      <mesh geometry={nodes.Neon.geometry} material={materials.Neon} position={[-3.619, 7.289, -0.006]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[-0.066, -16.558, -0.065]} />
      <mesh geometry={nodes.Neon001.geometry} material={materials['Neon.001']} position={[3.346, 7.289, -0.006]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[-0.066, -16.558, -0.065]} />
    </group>
  )
}

useGLTF.preload('/cinema8.glb')
