/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.12 C:\Users\fgarr\Documents\lab\youtube3d\apps\admin\public\assets\hub4.glb --types 
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube014: THREE.Mesh
    Cube015: THREE.Mesh
    Cube016: THREE.Mesh
    Mesh: THREE.Mesh
    Mesh_1: THREE.Mesh
    Cylinder: THREE.Mesh
    Cube017: THREE.Mesh
    Cube059: THREE.Mesh
    Cube059_1: THREE.Mesh
    Cube019: THREE.Mesh
    Plane_1: THREE.Mesh
    Plane_2: THREE.Mesh
    Plane_3: THREE.Mesh
    Plane_4: THREE.Mesh
    Plane_5: THREE.Mesh
    Plane_6: THREE.Mesh
    Plane_7: THREE.Mesh
    Plane_8: THREE.Mesh
    Plane_9: THREE.Mesh
    Plane_10: THREE.Mesh
    Plane_11: THREE.Mesh
    Plane_12: THREE.Mesh
    Plane_13: THREE.Mesh
    Plane_14: THREE.Mesh
    Plane_15: THREE.Mesh
    Plane_16: THREE.Mesh
    Cube020: THREE.Mesh
    Cube007: THREE.Mesh
    Cube007_1: THREE.Mesh
    Cube022: THREE.Mesh
    Cube023: THREE.Mesh
  }
  materials: {
    ['Marble.010']: THREE.MeshStandardMaterial
    ['Marble.011']: THREE.MeshStandardMaterial
    ['Marble.012']: THREE.MeshStandardMaterial
    ['01 - Default']: THREE.MeshStandardMaterial
    Marble: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    ['Glowing red']: THREE.MeshStandardMaterial
    ['Marble.003']: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
    ['Material.004']: THREE.MeshStandardMaterial
    ['Material.005']: THREE.MeshStandardMaterial
    ['Material.006']: THREE.MeshStandardMaterial
    ['Material.007']: THREE.MeshStandardMaterial
    ['Material.008']: THREE.MeshStandardMaterial
    ['Material.009']: THREE.MeshStandardMaterial
    ['Material.010']: THREE.MeshStandardMaterial
    ['Material.011']: THREE.MeshStandardMaterial
    ['Material.012']: THREE.MeshStandardMaterial
    ['Material.014']: THREE.MeshStandardMaterial
    ['Material.015']: THREE.MeshStandardMaterial
    ['Material.016']: THREE.MeshStandardMaterial
    ['Material.017']: THREE.MeshStandardMaterial
    ['Material.018']: THREE.MeshStandardMaterial
    ['Material.019']: THREE.MeshStandardMaterial
    ['Marble.013']: THREE.MeshStandardMaterial
    ['Glowing red.001']: THREE.MeshStandardMaterial
    ['Marble.014']: THREE.MeshStandardMaterial
    ['Marble.015']: THREE.MeshStandardMaterial
  }
}

type ActionName = 'DoorAction'
type GLTFActions = Record<ActionName, THREE.AnimationAction>

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials, animations } = useGLTF('/hub4.glb') as GLTFResult
  const { actions } = useAnimations<GLTFActions>(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Cube014" geometry={nodes.Cube014.geometry} material={materials['Marble.010']} position={[0.179, -10.514, 38.299]} rotation={[Math.PI / 2, 0, 0]} scale={[1.562, 1.289, 349.822]} />
        <mesh name="Cube015" geometry={nodes.Cube015.geometry} material={materials['Marble.011']} position={[0.413, 9.328, 59.773]} rotation={[Math.PI, 0, Math.PI / 2]} scale={[9.368, 37.699, 0.03]} />
        <mesh name="Cube016" geometry={nodes.Cube016.geometry} material={materials['Marble.012']} position={[0.413, 9.328, 16.967]} rotation={[Math.PI, 0, Math.PI / 2]} scale={[9.368, 37.699, 0.348]} />
        <group name="Door" position={[0.407, 4.033, 17.965]} rotation={[Math.PI / 2, 0, 0]} scale={[0.006, 0.003, 0.009]}>
          <mesh name="Mesh" geometry={nodes.Mesh.geometry} material={materials['01 - Default']} />
          <mesh name="Mesh_1" geometry={nodes.Mesh_1.geometry} material={materials.Marble} />
        </group>
        <mesh name="Cylinder" geometry={nodes.Cylinder.geometry} material={materials['Material.002']} position={[-0.142, -11.196, 52.246]} />
        <mesh name="Cube017" geometry={nodes.Cube017.geometry} material={materials.Marble} position={[-24.625, 0.439, 18.398]} />
        <group name="Cube018" position={[-22.733, 0.439, 26.231]}>
          <mesh name="Cube059" geometry={nodes.Cube059.geometry} material={materials['Glowing red']} />
          <mesh name="Cube059_1" geometry={nodes.Cube059_1.geometry} material={materials.Marble} />
        </group>
        <mesh name="Cube019" geometry={nodes.Cube019.geometry} material={materials['Marble.003']} position={[0.413, 19.004, 38.517]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[-21.804, -37.699, -0.339]} />
        <group name="Plane" position={[-27.339, 18.623, 23.772]} scale={[4.492, 1, 2.294]}>
          <mesh name="Plane_1" geometry={nodes.Plane_1.geometry} material={materials['Material.003']} />
          <mesh name="Plane_2" geometry={nodes.Plane_2.geometry} material={materials['Material.004']} />
          <mesh name="Plane_3" geometry={nodes.Plane_3.geometry} material={materials['Material.005']} />
          <mesh name="Plane_4" geometry={nodes.Plane_4.geometry} material={materials['Material.006']} />
          <mesh name="Plane_5" geometry={nodes.Plane_5.geometry} material={materials['Material.007']} />
          <mesh name="Plane_6" geometry={nodes.Plane_6.geometry} material={materials['Material.008']} />
          <mesh name="Plane_7" geometry={nodes.Plane_7.geometry} material={materials['Material.009']} />
          <mesh name="Plane_8" geometry={nodes.Plane_8.geometry} material={materials['Material.010']} />
          <mesh name="Plane_9" geometry={nodes.Plane_9.geometry} material={materials['Material.011']} />
          <mesh name="Plane_10" geometry={nodes.Plane_10.geometry} material={materials['Material.012']} />
          <mesh name="Plane_11" geometry={nodes.Plane_11.geometry} material={materials['Material.014']} />
          <mesh name="Plane_12" geometry={nodes.Plane_12.geometry} material={materials['Material.015']} />
          <mesh name="Plane_13" geometry={nodes.Plane_13.geometry} material={materials['Material.016']} />
          <mesh name="Plane_14" geometry={nodes.Plane_14.geometry} material={materials['Material.017']} />
          <mesh name="Plane_15" geometry={nodes.Plane_15.geometry} material={materials['Material.018']} />
          <mesh name="Plane_16" geometry={nodes.Plane_16.geometry} material={materials['Material.019']} />
        </group>
        <mesh name="Cube020" geometry={nodes.Cube020.geometry} material={materials['Marble.013']} position={[-36.938, 9.328, 38.412]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[-9.368, -22.057, -0.379]} />
        <group name="Cube021" position={[22.869, 0.439, 26.231]} rotation={[-Math.PI, 0, 0]} scale={-1}>
          <mesh name="Cube007" geometry={nodes.Cube007.geometry} material={materials['Glowing red.001']} />
          <mesh name="Cube007_1" geometry={nodes.Cube007_1.geometry} material={materials['Marble.014']} />
        </group>
        <mesh name="Cube022" geometry={nodes.Cube022.geometry} material={materials['Marble.014']} position={[24.761, 0.439, 18.398]} rotation={[-Math.PI, 0, 0]} scale={-1} />
        <mesh name="Cube023" geometry={nodes.Cube023.geometry} material={materials['Marble.015']} position={[37.153, 9.328, 38.412]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[-9.368, -22.057, -0.379]} />
      </group>
    </group>
  )
}

useGLTF.preload('/hub4.glb')
