/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 C:\Users\fgarr\Documents\lab\youtube3d\apps\admin\public\assets\hub5.glb --types 
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube014: THREE.Mesh
    Cube015: THREE.Mesh
    Cube016: THREE.Mesh
    Mesh: THREE.Mesh
    Mesh_1: THREE.Mesh
    Cylinder: THREE.Mesh
    Cube017: THREE.Mesh
    Cube059: THREE.Mesh
    Cube059_1: THREE.Mesh
    Cube019: THREE.Mesh
    Cube020: THREE.Mesh
    Cube007: THREE.Mesh
    Cube007_1: THREE.Mesh
    Cube022: THREE.Mesh
    Cube023: THREE.Mesh
    Plane009: THREE.Mesh
    Plane010: THREE.Mesh
    Plane011: THREE.Mesh
    Plane012: THREE.Mesh
    Plane013: THREE.Mesh
    Plane014: THREE.Mesh
    Plane015: THREE.Mesh
    Plane004: THREE.Mesh
    Plane005: THREE.Mesh
    Plane006: THREE.Mesh
    Plane007: THREE.Mesh
    Plane008: THREE.Mesh
    Plane016: THREE.Mesh
    Plane017: THREE.Mesh
    Plane018: THREE.Mesh
    Plane019: THREE.Mesh
  }
  materials: {
    ['Marble.010']: THREE.MeshStandardMaterial
    ['Marble.011']: THREE.MeshStandardMaterial
    ['Marble.012']: THREE.MeshStandardMaterial
    ['01 - Default']: THREE.MeshStandardMaterial
    Marble: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    ['Glowing red']: THREE.MeshStandardMaterial
    ['Marble.003']: THREE.MeshStandardMaterial
    ['Marble.013']: THREE.MeshStandardMaterial
    ['Glowing red.001']: THREE.MeshStandardMaterial
    ['Marble.014']: THREE.MeshStandardMaterial
    ['Marble.015']: THREE.MeshStandardMaterial
    ['Material.024']: THREE.MeshStandardMaterial
    ['Material.040']: THREE.MeshStandardMaterial
    ['Material.056']: THREE.MeshStandardMaterial
    ['Material.072']: THREE.MeshStandardMaterial
    ['Material.088']: THREE.MeshStandardMaterial
    ['Material.104']: THREE.MeshStandardMaterial
    ['Material.120']: THREE.MeshStandardMaterial
    ['Material.136']: THREE.MeshStandardMaterial
    ['Material.152']: THREE.MeshStandardMaterial
    ['Material.168']: THREE.MeshStandardMaterial
    ['Material.184']: THREE.MeshStandardMaterial
    ['Material.200']: THREE.MeshStandardMaterial
    ['Material.216']: THREE.MeshStandardMaterial
    ['Material.232']: THREE.MeshStandardMaterial
    ['Material.248']: THREE.MeshStandardMaterial
    ['Material.264']: THREE.MeshStandardMaterial
  }
}

type ActionName = 'DoorAction'
type GLTFActions = Record<ActionName, THREE.AnimationAction>

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials, animations } = useGLTF('/hub5.glb') as GLTFResult
  const { actions } = useAnimations<GLTFActions>(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Cube014" geometry={nodes.Cube014.geometry} material={materials['Marble.010']} position={[0.179, -10.514, 38.299]} rotation={[Math.PI / 2, 0, 0]} scale={[1.562, 1.289, 349.822]} />
        <mesh name="Cube015" geometry={nodes.Cube015.geometry} material={materials['Marble.011']} position={[0.413, 9.328, 59.773]} rotation={[Math.PI, 0, Math.PI / 2]} scale={[9.368, 37.699, 0.03]} />
        <mesh name="Cube016" geometry={nodes.Cube016.geometry} material={materials['Marble.012']} position={[0.413, 9.328, 16.967]} rotation={[Math.PI, 0, Math.PI / 2]} scale={[9.368, 37.699, 0.348]} />
        <group name="Door" position={[0.407, 4.033, 17.965]} rotation={[Math.PI / 2, 0, 0]} scale={[0.006, 0.003, 0.009]}>
          <mesh name="Mesh" geometry={nodes.Mesh.geometry} material={materials['01 - Default']} />
          <mesh name="Mesh_1" geometry={nodes.Mesh_1.geometry} material={materials.Marble} />
        </group>
        <mesh name="Cylinder" geometry={nodes.Cylinder.geometry} material={materials['Material.002']} position={[-0.142, -11.196, 52.246]} />
        <mesh name="Cube017" geometry={nodes.Cube017.geometry} material={materials.Marble} position={[-24.625, 0.439, 18.398]} />
        <group name="Cube018" position={[-22.733, 0.439, 26.231]}>
          <mesh name="Cube059" geometry={nodes.Cube059.geometry} material={materials['Glowing red']} />
          <mesh name="Cube059_1" geometry={nodes.Cube059_1.geometry} material={materials.Marble} />
        </group>
        <mesh name="Cube019" geometry={nodes.Cube019.geometry} material={materials['Marble.003']} position={[0.413, 19.004, 38.517]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[-21.804, -37.699, -0.339]} />
        <mesh name="Cube020" geometry={nodes.Cube020.geometry} material={materials['Marble.013']} position={[-36.938, 9.328, 38.412]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[-9.368, -22.057, -0.379]} />
        <group name="Cube021" position={[22.869, 0.439, 26.231]} rotation={[-Math.PI, 0, 0]} scale={-1}>
          <mesh name="Cube007" geometry={nodes.Cube007.geometry} material={materials['Glowing red.001']} />
          <mesh name="Cube007_1" geometry={nodes.Cube007_1.geometry} material={materials['Marble.014']} />
        </group>
        <mesh name="Cube022" geometry={nodes.Cube022.geometry} material={materials['Marble.014']} position={[24.761, 0.439, 18.398]} rotation={[-Math.PI, 0, 0]} scale={-1} />
        <mesh name="Cube023" geometry={nodes.Cube023.geometry} material={materials['Marble.015']} position={[37.153, 9.328, 38.412]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[-9.368, -22.057, -0.379]} />
        <mesh name="Plane009" geometry={nodes.Plane009.geometry} material={materials['Material.024']} position={[-27.349, 18.623, 23.67]} scale={[4.492, 1, 2.294]} />
        <mesh name="Plane010" geometry={nodes.Plane010.geometry} material={materials['Material.040']} position={[-27.58, 18.623, 34.275]} scale={[4.492, 1, 2.294]} />
        <mesh name="Plane011" geometry={nodes.Plane011.geometry} material={materials['Material.056']} position={[-27.349, 18.623, 44.403]} scale={[4.492, 1, 2.294]} />
        <mesh name="Plane012" geometry={nodes.Plane012.geometry} material={materials['Material.072']} position={[-27.349, 18.623, 53.211]} scale={[4.492, 1, 2.294]} />
        <mesh name="Plane013" geometry={nodes.Plane013.geometry} material={materials['Material.088']} position={[-8.58, 18.623, 53.211]} scale={[4.492, 1, 2.294]} />
        <mesh name="Plane014" geometry={nodes.Plane014.geometry} material={materials['Material.104']} position={[10.107, 18.623, 53.211]} scale={[4.492, 1, 2.294]} />
        <mesh name="Plane015" geometry={nodes.Plane015.geometry} material={materials['Material.120']} position={[29.479, 18.623, 53.211]} scale={[4.492, 1, 2.294]} />
        <mesh name="Plane004" geometry={nodes.Plane004.geometry} material={materials['Material.136']} position={[-8.826, 18.623, 44.403]} scale={[4.492, 1, 2.294]} />
        <mesh name="Plane005" geometry={nodes.Plane005.geometry} material={materials['Material.152']} position={[10.102, 18.623, 44.403]} scale={[4.492, 1, 2.294]} />
        <mesh name="Plane006" geometry={nodes.Plane006.geometry} material={materials['Material.168']} position={[29.596, 18.623, 44.403]} scale={[4.492, 1, 2.294]} />
        <mesh name="Plane007" geometry={nodes.Plane007.geometry} material={materials['Material.184']} position={[29.596, 18.623, 34.132]} scale={[4.492, 1, 2.294]} />
        <mesh name="Plane008" geometry={nodes.Plane008.geometry} material={materials['Material.200']} position={[10.102, 18.623, 34.132]} scale={[4.492, 1, 2.294]} />
        <mesh name="Plane016" geometry={nodes.Plane016.geometry} material={materials['Material.216']} position={[-8.826, 18.623, 34.132]} scale={[4.492, 1, 2.294]} />
        <mesh name="Plane017" geometry={nodes.Plane017.geometry} material={materials['Material.232']} position={[-8.942, 18.623, 23.562]} scale={[4.492, 1, 2.294]} />
        <mesh name="Plane018" geometry={nodes.Plane018.geometry} material={materials['Material.248']} position={[9.987, 18.623, 23.562]} scale={[4.492, 1, 2.294]} />
        <mesh name="Plane019" geometry={nodes.Plane019.geometry} material={materials['Material.264']} position={[29.481, 18.623, 23.562]} scale={[4.492, 1, 2.294]} />
      </group>
    </group>
  )
}

useGLTF.preload('/hub5.glb')
