/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 C:\Users\fgarr\Documents\lab\youtube3d\apps\admin\public\assets\hub9.glb --types 
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Fitness_Grandma_BodyGeo_1: THREE.SkinnedMesh
    Fitness_Grandma_BodyGeo_2: THREE.SkinnedMesh
    Fitness_Grandma_BrowsAnimGeo: THREE.SkinnedMesh
    Fitness_Grandma_EyesAnimGeo: THREE.SkinnedMesh
    Fitness_Grandma_MouthAnimGeo: THREE.SkinnedMesh
    Cube014: THREE.Mesh
    Cube015: THREE.Mesh
    Cube016: THREE.Mesh
    Mesh: THREE.Mesh
    Mesh_1: THREE.Mesh
    Cylinder: THREE.Mesh
    Cube017: THREE.Mesh
    Cube059: THREE.Mesh
    Cube059_1: THREE.Mesh
    Cube019: THREE.Mesh
    Cube020: THREE.Mesh
    Cube007_1: THREE.Mesh
    Cube007_2: THREE.Mesh
    Cube022: THREE.Mesh
    Cube023: THREE.Mesh
    Neon002: THREE.Mesh
    Neon003: THREE.Mesh
    Cube025: THREE.Mesh
    Cube026: THREE.Mesh
    Cube027: THREE.Mesh
    Cube028: THREE.Mesh
    Cube032: THREE.Mesh
    Cube033: THREE.Mesh
    Cube034: THREE.Mesh
    Cube037: THREE.Mesh
    Cube038: THREE.Mesh
    Cube039: THREE.Mesh
    Cube024: THREE.Mesh
    Cube029: THREE.Mesh
    Cube030: THREE.Mesh
    Cube031: THREE.Mesh
    Cube035: THREE.Mesh
    Cube036: THREE.Mesh
    Cube002: THREE.Mesh
    Cube004: THREE.Mesh
    Cube005: THREE.Mesh
    Cube006: THREE.Mesh
    Cube007: THREE.Mesh
    Cube008: THREE.Mesh
    Cube009: THREE.Mesh
    Cube010: THREE.Mesh
    stairs: THREE.Mesh
    Cube003: THREE.Mesh
    Neon: THREE.Mesh
    Neon001: THREE.Mesh
    collision_enter: THREE.Mesh
    collision_enter001: THREE.Mesh
    Cube: THREE.Mesh
    Cube001: THREE.Mesh
    Cube011: THREE.Mesh
    Cube012: THREE.Mesh
    Cube013: THREE.Mesh
    mixamorigHips: THREE.Bone
  }
  materials: {
    Grandma_MAT: THREE.MeshStandardMaterial
    Lens_MAT: THREE.MeshStandardMaterial
    FitGrandma_Brows_MAT1: THREE.MeshStandardMaterial
    FitGrandma_Eyes_MAT1: THREE.MeshStandardMaterial
    FitGrandma_Mouth_MAT1: THREE.MeshStandardMaterial
    ['Marble.010']: THREE.MeshStandardMaterial
    ['Marble.011']: THREE.MeshStandardMaterial
    ['Marble.012']: THREE.MeshStandardMaterial
    ['01 - Default']: THREE.MeshStandardMaterial
    Marble: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    ['Glowing red']: THREE.MeshStandardMaterial
    ['Marble.003']: THREE.MeshStandardMaterial
    ['Marble.013']: THREE.MeshStandardMaterial
    ['Glowing red.001']: THREE.MeshStandardMaterial
    ['Marble.014']: THREE.MeshStandardMaterial
    ['Marble.015']: THREE.MeshStandardMaterial
    ['Neon.002']: THREE.MeshStandardMaterial
    ['Neon.003']: THREE.MeshStandardMaterial
    ['Marble.016']: THREE.MeshStandardMaterial
    ['Plain.001']: THREE.MeshStandardMaterial
    ['Marble.017']: THREE.MeshStandardMaterial
    ['Marble.018']: THREE.MeshStandardMaterial
    ['black concrete.011']: THREE.MeshStandardMaterial
    ['black concrete.012']: THREE.MeshStandardMaterial
    ['black concrete.013']: THREE.MeshStandardMaterial
    ['black concrete.014']: THREE.MeshStandardMaterial
    ['black concrete.015']: THREE.MeshStandardMaterial
    ['black concrete.016']: THREE.MeshStandardMaterial
    ['black concrete.003']: THREE.MeshStandardMaterial
    ['black concrete.004']: THREE.MeshStandardMaterial
    ['black concrete.005']: THREE.MeshStandardMaterial
    ['black concrete.006']: THREE.MeshStandardMaterial
    ['black concrete.007']: THREE.MeshStandardMaterial
    ['black concrete.008']: THREE.MeshStandardMaterial
    Plain: THREE.MeshStandardMaterial
    ['Black concrete']: THREE.MeshStandardMaterial
    ['Plain black']: THREE.MeshStandardMaterial
    ['black concrete']: THREE.MeshStandardMaterial
    Neon: THREE.MeshStandardMaterial
    ['Neon.001']: THREE.MeshStandardMaterial
    ['Marble.004']: THREE.MeshStandardMaterial
    ['black concrete.002']: THREE.MeshStandardMaterial
  }
}

type ActionName = 'DoorAction' | 'Cube.021Action' | 'Cube.032Action' | 'Cube.033Action' | 'Cube.034Action' | 'Cube.034Action.001' | 'Cube.033Action.001' | 'Cube.032Action.001' | 'Armature|mixamo.com|Layer0' | 'Cube.032Action.002' | 'Cube.033Action.002' | 'Cube.034Action.002' | 'Cube.034Action.003' | 'Cube.033Action.003' | 'Cube.032Action.003' | 'Cube.001Action'
type GLTFActions = Record<ActionName, THREE.AnimationAction>

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['skinnedMesh'] | JSX.IntrinsicElements['mesh'] | JSX.IntrinsicElements['bone']>>

export function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials, animations } = useGLTF('/hub9.glb') as GLTFResult
  const { actions } = useAnimations<GLTFActions>(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" position={[17.587, 0, 36.383]} rotation={[Math.PI / 2, 0, 0]} scale={0.019}>
          <primitive object={nodes.mixamorigHips} />
          <group name="Fitness_Grandma_BodyGeo">
            <skinnedMesh name="Fitness_Grandma_BodyGeo_1" geometry={nodes.Fitness_Grandma_BodyGeo_1.geometry} material={materials.Grandma_MAT} skeleton={nodes.Fitness_Grandma_BodyGeo_1.skeleton} />
            <skinnedMesh name="Fitness_Grandma_BodyGeo_2" geometry={nodes.Fitness_Grandma_BodyGeo_2.geometry} material={materials.Lens_MAT} skeleton={nodes.Fitness_Grandma_BodyGeo_2.skeleton} />
          </group>
          <skinnedMesh name="Fitness_Grandma_BrowsAnimGeo" geometry={nodes.Fitness_Grandma_BrowsAnimGeo.geometry} material={materials.FitGrandma_Brows_MAT1} skeleton={nodes.Fitness_Grandma_BrowsAnimGeo.skeleton} />
          <skinnedMesh name="Fitness_Grandma_EyesAnimGeo" geometry={nodes.Fitness_Grandma_EyesAnimGeo.geometry} material={materials.FitGrandma_Eyes_MAT1} skeleton={nodes.Fitness_Grandma_EyesAnimGeo.skeleton} />
          <skinnedMesh name="Fitness_Grandma_MouthAnimGeo" geometry={nodes.Fitness_Grandma_MouthAnimGeo.geometry} material={materials.FitGrandma_Mouth_MAT1} skeleton={nodes.Fitness_Grandma_MouthAnimGeo.skeleton} />
        </group>
        <mesh name="Cube014" geometry={nodes.Cube014.geometry} material={materials['Marble.010']} position={[0.179, -10.489, 52.093]} rotation={[Math.PI / 2, 0, 0]} scale={[1.562, 1.289, 349.822]} />
        <mesh name="Cube015" geometry={nodes.Cube015.geometry} material={materials['Marble.011']} position={[0.413, 9.328, 73.466]} rotation={[Math.PI, 0, Math.PI / 2]} scale={[9.368, 37.699, 0.03]} />
        <mesh name="Cube016" geometry={nodes.Cube016.geometry} material={materials['Marble.012']} position={[0.413, 9.328, 30.761]} rotation={[Math.PI, 0, Math.PI / 2]} scale={[9.368, 37.699, 0.348]} />
        <group name="Door" position={[0.407, 4.033, 17.602]} rotation={[Math.PI / 2, 0, 0]} scale={[0.006, 0.003, 0.009]}>
          <mesh name="Mesh" geometry={nodes.Mesh.geometry} material={materials['01 - Default']} />
          <mesh name="Mesh_1" geometry={nodes.Mesh_1.geometry} material={materials.Marble} />
        </group>
        <mesh name="Cylinder" geometry={nodes.Cylinder.geometry} material={materials['Material.002']} position={[-0.142, -11.196, 66.04]} />
        <mesh name="Cube017" geometry={nodes.Cube017.geometry} material={materials.Marble} position={[-24.625, 0.439, 32.192]} />
        <group name="Cube018" position={[-22.733, 0.439, 40.025]}>
          <mesh name="Cube059" geometry={nodes.Cube059.geometry} material={materials['Glowing red']} />
          <mesh name="Cube059_1" geometry={nodes.Cube059_1.geometry} material={materials.Marble} />
        </group>
        <mesh name="Cube019" geometry={nodes.Cube019.geometry} material={materials['Marble.003']} position={[0.413, 19.004, 52.209]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[-21.804, -37.699, -0.339]} />
        <mesh name="Cube020" geometry={nodes.Cube020.geometry} material={materials['Marble.013']} position={[-36.938, 9.328, 52.206]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[-9.368, -22.057, -0.379]} />
        <group name="Cube021" position={[22.869, 0.356, 40.025]} rotation={[-Math.PI, 0, 0]} scale={-1}>
          <mesh name="Cube007_1" geometry={nodes.Cube007_1.geometry} material={materials['Glowing red.001']} />
          <mesh name="Cube007_2" geometry={nodes.Cube007_2.geometry} material={materials['Marble.014']} />
        </group>
        <mesh name="Cube022" geometry={nodes.Cube022.geometry} material={materials['Marble.014']} position={[24.761, 0.439, 32.192]} rotation={[-Math.PI, 0, 0]} scale={-1} />
        <mesh name="Cube023" geometry={nodes.Cube023.geometry} material={materials['Marble.015']} position={[37.153, 9.328, 52.206]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[-9.368, -22.057, -0.379]} />
        <mesh name="Neon002" geometry={nodes.Neon002.geometry} material={materials['Neon.002']} position={[3.346, 7.289, 24.857]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[-0.066, -5.961, -0.065]} />
        <mesh name="Neon003" geometry={nodes.Neon003.geometry} material={materials['Neon.003']} position={[-3.619, 7.289, 24.857]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[-0.066, -5.961, -0.065]} />
        <mesh name="Cube025" geometry={nodes.Cube025.geometry} material={materials['Marble.016']} position={[-4.896, 3.708, 24.859]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[1, 0.36, 40.262]} />
        <mesh name="Cube026" geometry={nodes.Cube026.geometry} material={materials['Plain.001']} position={[0, 7.377, 24.859]} rotation={[Math.PI / 2, 0, 0]} scale={[1, 0.36, 1]} />
        <mesh name="Cube027" geometry={nodes.Cube027.geometry} material={materials['Marble.017']} position={[-0.304, 0, 24.859]} rotation={[Math.PI / 2, 0, 0]} scale={[1, 0.36, 1]} />
        <mesh name="Cube028" geometry={nodes.Cube028.geometry} material={materials['Marble.018']} position={[4.616, 3.708, 24.859]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[1, 0.36, 40.262]} />
        <mesh name="Cube024" geometry={nodes.Cube024.geometry} material={materials['black concrete.003']} position={[30.39, 9.255, 31.221]} rotation={[0, Math.PI / 2, 0]} scale={2.193} />
        <mesh name="Cube029" geometry={nodes.Cube029.geometry} material={materials['black concrete.004']} position={[21.843, 9.255, 31.221]} rotation={[0, Math.PI / 2, 0]} scale={2.193} />
        <mesh name="Cube030" geometry={nodes.Cube030.geometry} material={materials['black concrete.005']} position={[13.295, 9.255, 31.221]} rotation={[0, Math.PI / 2, 0]} scale={2.193} />
        <mesh name="Cube031" geometry={nodes.Cube031.geometry} material={materials['black concrete.006']} position={[13.295, 14.572, 31.221]} rotation={[0, Math.PI / 2, 0]} scale={2.193} />
        <mesh name="Cube032" geometry={nodes.Cube032.geometry} material={materials['black concrete.011']} position={[30.39, 14.572, 31.221]} rotation={[0, Math.PI / 2, 0]} scale={2.193} />
        <mesh name="Cube033" geometry={nodes.Cube033.geometry} material={materials['black concrete.012']} position={[21.843, 14.572, 31.221]} rotation={[0, Math.PI / 2, 0]} scale={2.193} />
        <mesh name="Cube034" geometry={nodes.Cube034.geometry} material={materials['black concrete.013']} position={[13.295, 14.572, 31.221]} rotation={[0, Math.PI / 2, 0]} scale={2.193} />
        <mesh name="Cube035" geometry={nodes.Cube035.geometry} material={materials['black concrete.007']} position={[21.843, 14.572, 31.221]} rotation={[0, Math.PI / 2, 0]} scale={2.193} />
        <mesh name="Cube036" geometry={nodes.Cube036.geometry} material={materials['black concrete.008']} position={[30.39, 14.572, 31.221]} rotation={[0, Math.PI / 2, 0]} scale={2.193} />
        <mesh name="Cube037" geometry={nodes.Cube037.geometry} material={materials['black concrete.014']} position={[13.295, 9.255, 31.221]} rotation={[0, Math.PI / 2, 0]} scale={2.193} />
        <mesh name="Cube038" geometry={nodes.Cube038.geometry} material={materials['black concrete.015']} position={[21.843, 9.255, 31.221]} rotation={[0, Math.PI / 2, 0]} scale={2.193} />
        <mesh name="Cube039" geometry={nodes.Cube039.geometry} material={materials['black concrete.016']} position={[30.39, 9.255, 31.221]} rotation={[0, Math.PI / 2, 0]} scale={2.193} />
        <mesh name="Cube002" geometry={nodes.Cube002.geometry} material={materials.Marble} position={[-0.304, 0, 2.295]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Cube004" geometry={nodes.Cube004.geometry} material={materials.Plain} position={[0, 7.377, 2.295]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Cube005" geometry={nodes.Cube005.geometry} material={materials.Marble} position={[4.617, 9.36, 2.295]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[-1, -1, -40.426]} />
        <mesh name="Cube006" geometry={nodes.Cube006.geometry} material={materials['Black concrete']} position={[51.298, 9.36, 2.295]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} />
        <mesh name="Cube007" geometry={nodes.Cube007.geometry} material={materials.Marble} position={[27.615, 0.009, 2.295]} rotation={[Math.PI / 2, 0, 0]} scale={[1.009, 1, 1]} />
        <mesh name="Cube008" geometry={nodes.Cube008.geometry} material={materials.Marble} position={[27.69, 9.187, -14.232]} rotation={[Math.PI, 0, Math.PI / 2]} scale={[9.368, 23.816, 0.03]} />
        <mesh name="Cube009" geometry={nodes.Cube009.geometry} material={materials.Marble} position={[27.557, 9.328, 18.915]} rotation={[Math.PI, 0, Math.PI / 2]} scale={[9.368, 23.816, 0.03]} />
        <mesh name="Cube010" geometry={nodes.Cube010.geometry} material={materials['Plain black']} position={[27.722, 18.701, 2.46]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={[-1, -1, -10.203]} />
        <mesh name="stairs" geometry={nodes.stairs.geometry} material={materials.Marble} position={[21.291, 1.721, 8.555]} scale={[1, 1, 0.801]} />
        <mesh name="Cube003" geometry={nodes.Cube003.geometry} material={materials['black concrete']} position={[51.162, 10.214, 2.295]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={0.568} />
        <mesh name="Neon" geometry={nodes.Neon.geometry} material={materials.Neon} position={[-3.619, 7.289, 2.29]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[-0.066, -16.558, -0.065]} />
        <mesh name="Neon001" geometry={nodes.Neon001.geometry} material={materials['Neon.001']} position={[3.346, 7.289, 2.29]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[-0.066, -16.558, -0.065]} />
        <mesh name="collision_enter" geometry={nodes.collision_enter.geometry} material={nodes.collision_enter.material} position={[33.1, 4.273, -10.645]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-1, -4.581, -3.691]} />
        <mesh name="collision_enter001" geometry={nodes.collision_enter001.geometry} material={nodes.collision_enter001.material} position={[18.952, 0.36, -10.645]} scale={[13.404, 0.375, 3.691]} />
        <mesh name="Cube" geometry={nodes.Cube.geometry} material={materials.Marble} position={[21.836, 8.459, -4.457]} />
        <mesh name="Cube001" geometry={nodes.Cube001.geometry} material={materials['black concrete']} position={[3.354, 3.827, -6.98]} />
        <mesh name="Cube011" geometry={nodes.Cube011.geometry} material={materials['black concrete']} position={[-3.717, 3.673, -14.61]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} />
        <mesh name="Cube012" geometry={nodes.Cube012.geometry} material={materials['Marble.004']} position={[-4.896, 3.708, 2.295]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[1, 1, 40.262]} />
        <mesh name="Cube013" geometry={nodes.Cube013.geometry} material={materials['black concrete.002']} position={[3.514, 3.673, -14.61]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/hub9.glb')
